eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jingtingzhiwu/spring-cloud-parent-samples
          searchPaths: spring-cloud-config-profile/helloworld
  application:
    name: language-server
    
#netflix bus
  rabbitmq:
    host: 172.16.43.129
    port: 5672
    username: guest
    password: guest
    
#auto reload config
management:
  endpoints:
    web:
      exposure:
        include: "*"