eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jingtingzhiwu/spring-cloud-parent-samples
          searchPaths: spring-cloud-config-profile/helloworld
  application:
    name: language
    
#auto reload config
management:
  endpoints:
    web:
      exposure:
        include: "*"